service: serverless-backend

frameworkVersion: '3'

custom:
    stage: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-1'}
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        target: node20
        platform: node

provider:
    name: aws
    stage: ${self.custom.stage}
    runtime: nodejs20.x
    region: ${self.custom.region}

plugins:
    - serverless-offline
    - serverless-esbuild

functions:
    hello:
        handler: src/handlers/hello.handler
        events:
            - httpApi:
                  path: /hello
                  method: get
